apache/activemq-nms-amqp

HelloWorld/HelloWorld.csproj
NMS.AMQP/Apache-NMS-AMQP.csproj
StructuredMessage/StructuredMessage.csproj
src/main/csharp/Connection.cs
src/test/csharp/Test/Util/TestConfig.cs
test/Apache-NMS-AMQP-Test.csproj

- Add .NET Standard support
- Add nuget package configuration
- Update dependencies
- Add Microsoft.NET.Test.Sdk to be able to run tests directly form VS
- Get the directory containing the current test assembly properly
- Fix race condition on .NET Core
In previous implementation, CountDownLatch was instantiated after
OpenResponse subscription was made. It might lead to race conditions
when the connection was established before proper instance CountDownLatch
was set. As a result attempt to call Connect would end up with timeout.
For whatever reasons it wasn't a case with .NET Framework set as
a target framework, but happens every single time when you try to run
tests against .NET Core runtime.

AMQNET-585: NMS AMQP .NetStd 2.0 Client Support

---

src/NMS.AMQP/Message/Facade/INmsMessageFacade.cs
src/NMS.AMQP/Message/NmsMessage.cs
test/Apache-NMS-AMQP-Test/Message/Facade/NmsTestMessageFacade.cs
test/Apache-NMS-AMQP-Test/Message/NmsMessageTest.cs

It should be possible to set group-id message property using IMessage interface.

AMQNET-595: Set and get group-id message property field

---

src/NMS.AMQP/Provider/Amqp/AmqpSession.cs

The closed callback for sessions does not remove the AmqpSession from the AmqpConnection, unlike AmqpComsumer. Removing the explicit call to close leaves references in the AmqpConnection list for its AmqpSessions.

AMQNET-597: Remotely closed session is not removed from AmqpConnection

---

src/NMS.AMQP/Meta/ConnectionInfo.cs
src/NMS.AMQP/Meta/ConsumerInfo.cs
src/NMS.AMQP/NmsConnectionFactory.cs
src/NMS.AMQP/NmsMessageConsumer.cs
test/Apache-NMS-AMQP-Test/Integration/MessageExpirationIntegrationTest.cs
test/Apache-NMS-AMQP-Test/TestAmqp/TestAmqpPeer.cs
test/Apache-NMS-AMQP-Test/TestAmqp/TestMessageSource.cs

Message consumer only filter expired messages when local message expiry is enabled
Added message expiration integration test
Signed-off-by: cjwmorgan-sol <Christopher.Morgan@solace.com>

AMQNET-596: Added local message expiry connection uri connection property

---

src/NMS.AMQP/NmsQueue.cs
src/NMS.AMQP/NmsTemporaryQueue.cs
src/NMS.AMQP/NmsTemporaryTopic.cs
src/NMS.AMQP/NmsTopic.cs
test/Apache-NMS-AMQP-Test/NmsQueueTest.cs
test/Apache-NMS-AMQP-Test/NmsTemporaryQueueTest.cs
test/Apache-NMS-AMQP-Test/NmsTemporaryTopicTest.cs

This change is vital if one wants to use NMS AMQP with Spring CachingConnectionFactory, as current implementation prevents it from caching senders and consumers by destination.

AMQNET-600: Equals and GetHashCode should be overridden for IDestination implementations

---

src/NMS.AMQP/Message/Facade/INmsMessageFacade.cs
src/NMS.AMQP/Message/NmsMessage.cs
src/NMS.AMQP/NmsSession.cs
src/NMS.AMQP/Provider/Amqp/Message/AmqpNmsMessageFacade.cs
test/Apache-NMS-AMQP-Test/Message/Facade/NmsTestMessageFacade.cs
test/Apache-NMS-AMQP-Test/Provider/Amqp/AmqpNmsMessageFacadeTest.cs

This PR removes workaround https://github.com/apache/activemq-nms-amqp/commit/3c154aa7327b31a905b4b0c7d9df514f56b81960.

AMQNET-607: It should be possible to reset AbsoluteExpiryTime

---

src/NMS.AMQP/Apache-NMS-AMQP.csproj
src/NMS.AMQP/Provider/Amqp/AmqpConnection.cs
src/NMS.AMQP/Provider/Amqp/AmqpHandler.cs
src/NMS.AMQP/Provider/Amqp/AmqpProducer.cs
src/NMS.AMQP/Transport/ITransportContext.cs
src/NMS.AMQP/Transport/SecureTransportContext.cs
src/NMS.AMQP/Transport/TransportContext.cs
test/Apache-NMS-AMQP-Test/Integration/ProducerIntegrationTest.cs
test/Apache-NMS-AMQP-Test/TestAmqp/TestAmqpPeer.cs

This PR resolves the performance issue with brokers that respect the batchable flag for amqp transfer. https://github.com/apache/activemq-nms-amqp/pull/8#issuecomment-517366025
It utilizes new Handel API of amqp net lite, and new testing toolkit, and thus we should wait with merge until https://github.com/Azure/amqpnetlite/commit/2c38af646de695c17ccccf6f6992fbeecd2a0252 is released and https://github.com/apache/activemq-nms-amqp/pull/9 is merged. 
Moreover it illustrates the problem pointed out by @cjwmorgan-sol https://github.com/apache/activemq-nms-amqp/pull/9#issuecomment-521632602. **TestSendingMessageNonPersistentSetsBatchableFalse** is failing because of that. I think this issue should be addressed with higher precedence.
Prerequisites:

AMQNET-602: Set batchable flag to false for amqp transfer

---

src/NMS.AMQP/Apache-NMS-AMQP.csproj
src/NMS.AMQP/Provider/Amqp/AmqpConnection.cs
src/NMS.AMQP/Provider/Amqp/AmqpHandler.cs
src/NMS.AMQP/Provider/Amqp/AmqpProducer.cs
src/NMS.AMQP/Transport/ITransportContext.cs
src/NMS.AMQP/Transport/SecureTransportContext.cs
src/NMS.AMQP/Transport/TransportContext.cs
test/Apache-NMS-AMQP-Test/Integration/ProducerIntegrationTest.cs
test/Apache-NMS-AMQP-Test/TestAmqp/TestAmqpPeer.cs

This PR resolves https://issues.apache.org/jira/browse/AMQNET-608

AMQNET-608: Provider shouldn't sent transfer frames as settled

---

src/NMS.AMQP/Provider/Amqp/AmqpConnection.cs
src/NMS.AMQP/Provider/Amqp/AmqpProvider.cs
test/Apache-NMS-AMQP-Test/Integration/ConnectionIntegrationTest.cs

AmqpProvider shouldn't signal exception when connection is explicitly closed. It may lead to deadlocks when provider is used with Spring SimpleMessageListenerContainer.
This PR addresses this issue. 
@cjwmorgan-sol Could you please take a look at this? It is implemented according to your suggestion.

AMQNET-603: AmqpProvider shouldn't signal exception when connection is explicitly closed

---

src/NMS.AMQP/NmsConnection.cs
src/NMS.AMQP/NmsMessageConsumer.cs
test/Apache-NMS-AMQP-Test/Integration/FailoverIntegrationTest.cs

There is a discrepancy between current implementation and qpid-jms that may cause consumer to stop processing messages. 
There may be an exception throw in NmsMessageConsumer.cs DeliverNextPending method which results in taking down SessionDispatcher. There are two cases when we can get an error here:
1) error returned from the attempted ACK that was sent
2) error while attempting to copy the incoming message. 
In qpid-jms this is addressed with simple try/catch statement, and the error is redirected to connection ExceptionListener. 
@michaelandrepearce @cjwmorgan-sol Could you please take a look at it?

AMQNET-609: Error during message delivery may block consumer

---

src/NMS.AMQP/Message/Facade/INmsMessageFacade.cs
src/NMS.AMQP/Provider/Amqp/Message/AmqpCodec.cs
src/NMS.AMQP/Provider/Amqp/Message/AmqpNmsBytesMessageFacade.cs
src/NMS.AMQP/Provider/Amqp/Message/AmqpNmsMapMessageFacade.cs
src/NMS.AMQP/Provider/Amqp/Message/AmqpNmsMessageFacade.cs
src/NMS.AMQP/Provider/Amqp/Message/AmqpNmsObjectMessageFacade.cs
src/NMS.AMQP/Provider/Amqp/Message/AmqpNmsStreamMessageFacade.cs
src/NMS.AMQP/Provider/Amqp/Message/AmqpNmsTextMessageFacade.cs
test/Apache-NMS-AMQP-Test/Message/Facade/NmsTestMessageFacade.cs
test/Apache-NMS-AMQP-Test/Provider/Amqp/AmqpCodecTest.cs
test/Apache-NMS-AMQP-Test/Provider/Amqp/AmqpMessageFactoryTest.cs
test/Apache-NMS-AMQP-Test/Provider/Amqp/AmqpNmsObjectMessageFacadeTest.cs

It addresses https://issues.apache.org/jira/browse/AMQNET-612
I tested it with qpid-jms and it seems to work fine, when .net is a producer and java is a consumer. There is a problem however when the roles change. We still try to interpret object "x-opt-jms-msg-type" for the sake of AmqpTypedObjects but when we receive java serialized payload it breaks. Should we resign from x-opt-jms-msg-type object whatsoever?

AMQNET-612: ObjectMessage shouldn't have jms-msg-type set

---

src/NMS.AMQP/NmsMessageConsumer.cs

NmsMessageConsumer takes a lock on a static field, in order to support serial execution of messages. As a result messages are delivered in serial order even if the consumers do not share the same session.

AMQNET-615: NmsMessageConsumer takes a lock on a static field

---

src/NMS.AMQP/NmsConnectionFactory.cs
test/Apache-NMS-AMQP-Test/ConnectionFactoryTest.cs

ConnectionFactory was not initialized properly with constructor that takes System.Uri as a parameter. Additional properties that were specified in broker uri (like username or password) were not applied on connection factory.

AMQNET-620: Initialize ConnectionFactory properly with System.Uri overload

---

apache-nms-amqp.sln.DotSettings
src/NMS.AMQP/Apache-NMS-AMQP.csproj
src/NMS.AMQP/NmsLocalTransactionContext.cs
src/NMS.AMQP/NmsSession.cs
src/NMS.AMQP/Provider/Amqp/AmqpConsumer.cs
src/NMS.AMQP/Provider/Amqp/AmqpLinkExtensions.cs
src/NMS.AMQP/Provider/Amqp/AmqpProducer.cs
src/NMS.AMQP/Provider/Amqp/AmqpSendTask.cs
src/NMS.AMQP/Provider/Amqp/AmqpSession.cs
src/NMS.AMQP/Provider/Amqp/AmqpTransactionContext.cs
src/NMS.AMQP/Provider/Amqp/AmqpTransactionCoordinator.cs
test/Apache-NMS-AMQP-Test/Integration/FailoverIntegrationTest.cs
test/Apache-NMS-AMQP-Test/Integration/ProducerIntegrationTest.cs
test/Apache-NMS-AMQP-Test/Integration/TransactionsIntegrationTest.cs
test/Apache-NMS-AMQP-Test/TestAmqp/TestAmqpPeer.cs

Our implementation of transactions in NMS-AMQP was passable, but not 100% in line with spec and qpid-jms.
This PR introduces several adjustments (mostly timeouts on transaction related operations) and several integration tests that helped me adjust the implementation. 
Changes introduced in this PR depend on https://github.com/Azure/amqpnetlite/pull/385 and https://github.com/Azure/amqpnetlite/pull/388 and cannot be merged until new version of https://github.com/Azure/amqpnetlite is released. 
@michaelandrepearce @cjwmorgan-sol Could you please take a look at this?
@xinchen10 When can we expect the next minor release of AMQP.Net Lite?

AMQNET-627: Transactions implementation adjustments

---

src/NMS.AMQP/NmsMessageProducer.cs
test/Apache-NMS-AMQP-Test/Integration/ProducerIntegrationTest.cs
test/Apache-NMS-AMQP-Test/NmsMessageProducerTest.cs

This closes https://issues.apache.org/jira/browse/AMQNET-634.

AMQNET-634: Use 4 as default msg priority

---

src/NMS.AMQP/Apache-NMS-AMQP.csproj

Previous version of AmqpNetLite doesn't support TcpKeepAliveSettings on Linux.

AMQNET-635: Update AMQPNetLite.Core to 2.4.0 version

---

package.ps1
src/NMS.AMQP/Apache-NMS-AMQP.csproj

I'd like to add SourceLink support to this library in order to simplify debugging from referencing projects.
It would be great to first merge [AMQNET-638 Add SourceLink support](https://github.com/apache/activemq-nms-api/pull/13) and then update [Apache.NMS](https://github.com/apache/activemq-nms-amqp/blob/f1b1f67e1d15b714d7a7c2c827ceeac9978b7a33/src/NMS.AMQP/Apache-NMS-AMQP.csproj#L84) package reference to v.1.8.1
Please take a look into the small demo of SourceLink in action 
For more details on how to enable debugging with SourceLink please check the following guides:
- [How to Configure Visual Studio to Use SourceLink to Step into NuGet Package Source](http://www.aaronstannard.com/visual-studio-sourcelink-setup/)
- [Debugging into NuGet packages with SourceLink in Visual Studio for …

AMQNET-639 Add SourceLink support

---

.travis.yml
src/HelloWorld/HelloWorld.csproj
src/PingPong/PingPong.csproj
src/StructuredMessage/StructuredMessage.csproj
src/Transactions/Transactions.csproj
test/Apache-NMS-AMQP-Interop-Test/Apache-NMS-AMQP-Interop-Test.csproj
test/Apache-NMS-AMQP-Test/Apache-NMS-AMQP-Test.csproj

_This pull request is not necessarily proposed to merge, but is more for discussion - and also for a test to see what Travis CI does with it._
As .NET Core 2.2 has reached end of life, I tried switching the references back to 2.1 which is still supported at this time (albeit only until August). This affects the test suite, the samples, and the CI config. The main output package, targeting .NET Standard 2.0, is unchanged. As far as I can tell, it didn't cause any problems building and testing locally.
It is noted that this PR is mutually exclusive with #49 which contemplates upgrading to .NET Core 3.0; but that 3.0 is also EOL. I would be happy with bumping that to 3.1, and seeing that merged in lieu of this PR - I don't usually target 2.1 anymore myself. However, there was discussion in …

NO-JIRA: Switch .NET Core targets from 2.2 (no longer supported) back to 2.1 (LTS)

---

src/NMS.AMQP/Provider/Amqp/AmqpConsumer.cs
test/Apache-NMS-AMQP-Test/Integration/AmqpAcknowledgmentsIntegrationTest.cs

This pull request adds the ability to acknowledge messages with MODIFIED_FAILED, instead of MODIFIED_FAILED_UNDELIVERABLE. 
A very basic example below:
```csharp
private void ReceiveMessage(IMessage message)
{
var txt = message.Body<string>();
_logger.LogInformation("message received: {Content}", txt);
if (txt.Contains('5') && message is NmsMessage msg)
{
msg.NmsAcknowledgeCallback.AcknowledgementType = AckType.MODIFIED_FAILED;
}
message.Acknowledge();
}
```
As far as i can see, this method is the only way to acknowledge a failure when using `AcknowledgementMode.IndividualAcknowledge`
I tested this with an artemis broker, and all tests still run fine.

AMQNET-831 allow acktype modified_failed

---

src/NMS.AMQP/Message/NmsMessage.cs
src/NMS.AMQP/Message/NmsMessagePropertiesInterceptor.cs
test/Apache-NMS-AMQP-Test/Integration/AmqpAcknowledgmentsIntegrationTest.cs
test/Apache-NMS-AMQP-Test/Message/NmsMessageTest.cs

This PR is a follow up to  #86. It adds option to change the AcknowledgementType via message properties. The implementation is based on qpid-jms. Additionally I reimplemented the message properties interceptor. The new implementation doesn't use reflection anymore.

AMQNET-831 Add option to change ack mode via message properties

---

test/Apache-NMS-AMQP-Test/Integration/FailoverIntegrationTest.cs

The test referenced in this issue is actually fixed. The ignore attribute can be safely deleted

AMQNET-606: Ignore can be removed. test works
